export const weatherLocalization = {
  ja: {
    "Thunderstorm with light rain": "雷雨と小雨",
    "Thunderstorm with rain": "雷雨と雨",
    "Thunderstorm with heavy rain": "雷雨と大雨",
    "Light thunderstorm": "弱い雷雨",
    "Thunderstorm": "雷雨",
    "Heavy thunderstorm": "強い雷雨",
    "Ragged thunderstorm": "散在する雷雨",
    "Thunderstorm with light drizzle": "雷雨と弱い霧雨",
    "Thunderstorm with drizzle": "雷雨と霧雨",
    "Thunderstorm with heavy drizzle": "雷雨と強い霧雨",
    "Light intensity drizzle": "弱い霧雨",
    "Drizzle": "霧雨",
    "Heavy intensity drizzle": "強い霧雨",
    "Light intensity drizzle rain": "弱い霧雨の雨",
    "Drizzle rain": "霧雨の雨",
    "Heavy intensity drizzle rain": "強い霧雨の雨",
    "Shower rain and drizzle": "にわか雨と霧雨",
    "Heavy shower rain and drizzle": "強いにわか雨と霧雨",
    "Shower drizzle": "にわか霧雨",
    "Light rain": "小雨",
    "Moderate rain": "適度な雨",
    "Heavy intensity rain": "強い雨",
    "Very heavy rain": "非常に強い雨",
    "Extreme rain": "激しい雨",
    "Freezing rain": "氷雨",
    "Light intensity shower rain": "弱いにわか雨",
    "Shower rain": "にわか雨",
    "Heavy intensity shower rain": "強いにわか雨",
    "Ragged shower rain": "散在するにわか雨",
    "Light snow": "小雪",
    "Snow": "雪",
    "Heavy snow": "大雪",
    "Sleet": "みぞれ",
    "Light shower sleet": "弱いにわかみぞれ",
    "Shower sleet": "にわかみぞれ",
    "Light rain and snow": "弱い雨と雪",
    "Rain and snow": "雨と雪",
    "Light shower snow": "弱いにわか雪",
    "Shower snow": "にわか雪",
    "Heavy shower snow": "強いにわか雪",
    "Mist": "霧",
    "Smoke": "煙霧",
    "Haze": "薄霧",
    "Sand/Dust whirls": "砂塵旋風",
    "Fog": "濃霧",
    "Sand": "砂嵐",
    "Dust": "粉塵",
    "Volcanic ash": "火山灰",
    "Squalls": "スコール",
    "Tornado": "竜巻",
    "Clear sky": "快晴",
    "Few clouds": "薄い雲",
    "Scattered clouds": "点在する雲",
    "Broken clouds": "曇りがち",
    "Overcast clouds": "曇天"
  },
  zh: {
    "Thunderstorm with light rain": "雷暴伴小雨",
    "Thunderstorm with rain": "雷暴伴雨",
    "Thunderstorm with heavy rain": "雷暴伴大雨",
    "Light thunderstorm": "轻度雷暴",
    "Thunderstorm": "雷暴",
    "Heavy thunderstorm": "强雷暴",
    "Ragged thunderstorm": "不规则雷暴",
    "Thunderstorm with light drizzle": "雷暴伴轻毛毛雨",
    "Thunderstorm with drizzle": "雷暴伴毛毛雨",
    "Thunderstorm with heavy drizzle": "雷暴伴大毛毛雨",
    "Light intensity drizzle": "轻微毛毛雨",
    "Drizzle": "毛毛雨",
    "Heavy intensity drizzle": "强毛毛雨",
    "Light intensity drizzle rain": "轻微毛毛细雨",
    "Drizzle rain": "毛毛细雨",
    "Heavy intensity drizzle rain": "强毛毛细雨",
    "Shower rain and drizzle": "阵雨与毛毛雨",
    "Heavy shower rain and drizzle": "强阵雨与毛毛雨",
    "Shower drizzle": "阵毛毛雨",
    "Light rain": "小雨",
    "Moderate rain": "中雨",
    "Heavy intensity rain": "大雨",
    "Very heavy rain": "暴雨",
    "Extreme rain": "特大暴雨",
    "Freezing rain": "冻雨",
    "Light intensity shower rain": "轻阵雨",
    "Shower rain": "阵雨",
    "Heavy intensity shower rain": "强阵雨",
    "Ragged shower rain": "不规则阵雨",
    "Light snow": "小雪",
    "Snow": "雪",
    "Heavy snow": "大雪",
    "Sleet": "雨夹雪",
    "Light shower sleet": "轻阵雨夹雪",
    "Shower sleet": "阵雨夹雪",
    "Light rain and snow": "小雨夹雪",
    "Rain and snow": "雨夹雪",
    "Light shower snow": "轻阵雪",
    "Shower snow": "阵雪",
    "Heavy shower snow": "强阵雪",
    "Mist": "薄雾",
    "Smoke": "烟雾",
    "Haze": "霾",
    "Sand/Dust whirls": "沙尘旋风",
    "Fog": "雾",
    "Sand": "沙尘暴",
    "Dust": "尘土",
    "Volcanic ash": "火山灰",
    "Squalls": "飑风",
    "Tornado": "龙卷风",
    "Clear sky": "晴天",
    "Few clouds": "少云",
    "Scattered clouds": "疏云",
    "Broken clouds": "多云",
    "Overcast clouds": "阴天"
  },
  es: {
    "Thunderstorm with light rain": "Tormenta con lluvia ligera",
    "Thunderstorm with rain": "Tormenta con lluvia",
    "Thunderstorm with heavy rain": "Tormenta con lluvia intensa",
    "Light thunderstorm": "Tormenta ligera",
    "Thunderstorm": "Tormenta",
    "Heavy thunderstorm": "Tormenta fuerte",
    "Ragged thunderstorm": "Tormenta irregular",
    "Thunderstorm with light drizzle": "Tormenta con llovizna ligera",
    "Thunderstorm with drizzle": "Tormenta con llovizna",
    "Thunderstorm with heavy drizzle": "Tormenta con llovizna intensa",
    "Light intensity drizzle": "Llovizna ligera",
    "Drizzle": "Llovizna",
    "Heavy intensity drizzle": "Llovizna intensa",
    "Light intensity drizzle rain": "Lluvia de llovizna ligera",
    "Drizzle rain": "Lluvia de llovizna",
    "Heavy intensity drizzle rain": "Lluvia de llovizna intensa",
    "Shower rain and drizzle": "Chubasco y llovizna",
    "Heavy shower rain and drizzle": "Fuerte chubasco y llovizna",
    "Shower drizzle": "Chubasco de llovizna",
    "Light rain": "Lluvia ligera",
    "Moderate rain": "Lluvia moderada",
    "Heavy intensity rain": "Lluvia intensa",
    "Very heavy rain": "Lluvia muy intensa",
    "Extreme rain": "Lluvia extrema",
    "Freezing rain": "Lluvia helada",
    "Light intensity shower rain": "Chubasco de baja intensidad",
    "Shower rain": "Chubasco",
    "Heavy intensity shower rain": "Chubasco intenso",
    "Ragged shower rain": "Chubasco irregular",
    "Light snow": "Nieve ligera",
    "Snow": "Nieve",
    "Heavy snow": "Nieve intensa",
    "Sleet": "Aguanieve",
    "Light shower sleet": "Aguanieve ligera",
    "Shower sleet": "Aguanieve",
    "Light rain and snow": "Lluvia y nieve ligera",
    "Rain and snow": "Lluvia y nieve",
    "Light shower snow": "Chubasco de nieve ligera",
    "Shower snow": "Chubasco de nieve",
    "Heavy shower snow": "Chubasco de nieve intensa",
    "Mist": "Neblina",
    "Smoke": "Humo",
    "Haze": "Calina",
    "Sand/Dust whirls": "Remolinos de arena/polvo",
    "Fog": "Niebla",
    "Sand": "Arena",
    "Dust": "Polvo",
    "Volcanic ash": "Ceniza volcánica",
    "Squalls": "Ráfagas",
    "Tornado": "Tornado",
    "Clear sky": "Cielo despejado",
    "Few clouds": "Pocas nubes",
    "Scattered clouds": "Nubes dispersas",
    "Broken clouds": "Nubes rotas",
    "Overcast clouds": "Cielo cubierto"
  }
}
